### ISSUE TITLE
Missing word: commentor

### ISSUE THREAD

**Issue by cheesecracker** [cybrkyd/british-english-language-tools#4]
Hello,

The word "commentor(s)" is missing in the dictionary:
https://www.merriam-webster.com/dictionary/commenter
https://www.collinsdictionary.com/dictionary/english/commentor

Thank you and cheer

**Comment by cybrkyd** [comment]
Many such nouns are missing as they tend to be used mostly as part of US day-to-day English. However, this one is interesting, as it is now becoming a bit more common, particularly in reference to the Internet. I will add into next update.

**Comment by cheesecracker** [comment]
This one is British English.  So it should certainly interest you 😊

**Comment by cybrkyd** [comment]
Added
