### ISSUE TITLE
Dictionary word change

### ISSUE THREAD

**Issue by Futuro2011** [cybrkyd/british-english-language-tools#5]
Although the word "program/programs" is accepted in EN-UK, the correct British spelling would be "programme/programmes" instead.

**Comment by cybrkyd** [comment]
Agree - "programme/programmes" is British English standard except for when the word "program" is used in the context of computing. For example, it would be correct to write "Microsoft Office is a computer program" as opposed to "Microsoft Office is a computer programme". See refs:
1. https://www.oxfordlearnersdictionaries.com/definition/english/program_1?q=program
2. https://dictionary.cambridge.org/dictionary/english/program
